repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.280
  hooks:
    - id: ruff

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.11
